name: SubInventory
main: DeBePlugins\SubInventory\SubInventory
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 echest:
  permission: debe.echest.cmd
  description: SubInventory - Command
  usage: /SubInventory

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.echest.cmd:
    default: true
    description: Enderchest - Command
