name: TeleportView
main: DeBePlugins\TeleportView\TeleportView
version: 1.0.1_for1.4
api: [1.4.0]
author: if(Team);-DeBe

commands:
 teleportview:
  permission: db.pl.teleportview
  description: DeBe's TeleportView - Player
  usage: /TeleportView

permissions:
 db.pl:
  default: true
  description: DeBe's Plugins for Player
  children:
   db.pl.teleportview:
    description: DeBe's TeleportView - for Player