name: ViewLocation
main: DeBePlugins\ViewLocation\ViewLocation
version: 1.0.1_for1.4
api: [1.4.0]
author: if(Team);-DeBe

commands:
 viewlocation:
  permission: db.pl.viewlocation
  description: DeBe's ViewLocation - for Player
  usage: /ViewLocation <PlayerName>

permissions:
 db.pl:
  default: true
  description: DeBe's Plugins for Player
  children:
   db.pl.viewlocation:
    description: DeBe's ViewLocation- for Player